openapi: 3.0.0

info:
    title: GitHub Advanced Security for GitHub Organizations
    description: Skills to retrieve Code Scanning, Dependabot Scanning and Secret Scanning alerts for the default branch of
        all the repositiories (repo) of the specified Organization in GitHub. 
        These scannings are executed by GitHub Advanced Security (GhAS).
    version: "0.0.1"

paths:
  https://api.github.com/repos/{org}/{repository}/contents/{sub_path}:
    get:
      operationId: GetSampleGitHubRepositoryFileList
      summary: >
        Get the list of files from a GitHub repository. Each item will have a 'path' and the 'type'.
        If the 'type' is 'file', add it to the output list. In case the 'type' is 'dir', substitute
        that in 'sub_path' and call this skill again. Add the output to the original list of files.
      parameters:
        - in: path
          name: org
          schema:
            type: string
          required: true
          description: GitHub organization name.
        - in: path
          name: repository
          schema:
            type: string
          required: true
          description: GitHub repository name.
        - in: path
          name: sub_path
          schema:
            type: string
          required: false
          description: Sub-path inside the GitHub repository.
        - in: header
          name: User-Agent 
          schema:
            type: string
          required: true
          description: User-Agent (You can write any text here. This parameter is added as a temporary workaround to make the call succeed)          
      responses:
        '200':
          description: Successful retrieval of list.
        '401':
          description: Unsuccessful authentication.

